# Generated by Django 5.0 on 2024-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
