# Generated by Django 5.0 on 2023-12-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='fork',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='fork_setting',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='shock',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='shock_setting',
        ),
        migrations.DeleteModel(
            name='Fork',
        ),
        migrations.DeleteModel(
            name='Fork_Setting',
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
        migrations.DeleteModel(
            name='Shock',
        ),
        migrations.DeleteModel(
            name='Shock_Setting',
        ),
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
