# Generated by Django 5.0 on 2023-12-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='eye_to_eye',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='stroke',
        ),
    ]
