# Generated by Django 5.0 on 2023-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_bike_eye_to_eye_remove_bike_stroke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='progression',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
