# Generated by Django 5.0 on 2023-12-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_variations_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='fork',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='shock',
        ),
    ]
