# Generated by Django 5.0 on 2024-01-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_variation_fork_remove_variation_shock'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
