# Generated by Django 5.0 on 2024-01-21 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_setup_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.setup_folder'),
        ),
    ]
