# Generated by Django 5.0 on 2024-01-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_setup_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Setup_Folder',
        ),
    ]
